server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    location = / {
        return 302 /es;
    }

    location /api/ {
        set $contact_api_upstream contact-api:8080;
        proxy_pass http://$contact_api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
